#!/bin/bash
cd ~
rm -rf ~/blocked.rsc
rm -rf ~/all.txt
rm -rf ~/all.txt*

wget https://blacklist.3coresec.net/lists/all.txt

echo "/ip/firewall/address-list" > ~/blocked.rsc
echo "/ip firewall address-list remove [find list=blocked]" >> ~/blocked.rsc

while read -r ip; do
  echo "add list=blocked address=$ip comment=\"genarate from a script on yourLinuxserverip\"" >> ~/blocked.rsc
done < ~/all.txt
scp ./blocked.rsc root@yourRouterOSip:/
ssh admin@yourRouterOSip '/import file-name=blocked.rsc'
